flaskService:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort
flaskapiDeployment:
  flaskapi:
    env:
      dbName: flaskapi
    image:
      repository: igbedo/flaskapp
      tag: 1.1.1 
    imagePullPolicy: Always
  replicas: 3
flaskapiSecrets:
  dbRootPassword: "admin"
kubernetesClusterDomain: cluster.local
mysql:
  mysql:
    image:
      repository: mysql
      tag: latest
    imagePullPolicy: Always
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 0
  replicas: 1
  type: NodePort
pvc:
  mysqlPvClaim:
    storageClass: manual
    storageRequest: 2Gi
