apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskapi-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/igbedo/flaskapp-argo-image-updater'
    path: .
    targetRevision: HEAD
    path: staging/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
